### ISSUE TITLE
Dockerize Micro-Services - Central Directory

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#10]
##### Description:
Central Directory API to run via Docker

##### Success Criteria:
- Dockerfile recipe which executes the NodeJs.
- Docker image successfully created for API
- Docker image can be executed to run the API
- Publish Docker Image to https://hub.docker.com/r/mojaloop

**Comment by elnyry** [comment]
Outdated; current issues tracked here - https://github.com/mojaloop/project/issues
