### ISSUE TITLE
Re-factor Mock-pathfinder micro-service for K8 Pods and Deployments utilizing K8 DNS for Service Discovery, Database, Health Probe, Configurations and Secrets

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#101]
##### Description:
Mock-pathfinder to deploy and run via a Kubernetes

##### Success Criteria:
- Define Kubernetes Deployment Templates (Pod, Services, Ingress)
- Inject Environmental Configurations via ConfigMaps into the Container Runtime
- Inject hashed sensitive information (e.g. credentials) via a Secret into the Container Runtime
- Configure Health Probe (if available)

**Comment by elnyry** [comment]
Created - https://github.com/mojaloop/project/issues/495 under mojaloop/project
