### ISSUE TITLE
Deployment documentation Updates

### ISSUE THREAD

**Issue by kjw000** [mojaloop/mojaloop#120]
Update pre-requisites document to better understand the requirements for installing Mojaloop.

Issue #1:
1. Vagrant (for specific configs outside default, there should be additional documentation that lists these changes prior to getting into the download/cloning of the repo)
	2. VirtualBox (If a new VM needs to be set up, some specifics on the VM are needed (Supported OS's, CPU/RAM/DISK/Network requirements))
	3. An ssh client (Git for Windows can be used to get a full ssh client)
	4. AWS credential and config information (only for AWS installs)
From <https://github.com/mojaloop/interop-devops/blob/master/README.md> 

Issue #2:
This is in the documentation for standalone, however, is this from a Windows/MAC/Linux perspective?
What are the requirements for Vagrant (specific min version)
VirtualBox, do I need this to stand up a Standalone Server? If so, what are the requirements? (CPU/RAM/Disk)?
Are we are running these commands. Local Machine (Windows/MAC/Linux) or from the machine we stood up in Virtual Box (which we need to know has to be done).
Requirements mention nothing about needing Ansible (can it be run from the virtual machine host or needs to be run on the virtual machine itself?)

Issue #3 
Configuration
Changes required for Windows 10:
VirtualBox and Hyper-V conflict and cause a blue screen crash. For this reason and other intricacies of Hyper-V, it is best to disable Hyper-V and use Virtual Box.
From <https://github.com/mojaloop/interop-devops> 
Does this ONLY work with VirtualBox or can a Hyper-V images be used? In my case, I run VM's on Hyper-V and would cause more issues to disable to run in VirtualBox only as I have Hyper-V VM's running all the time. How often does this issue manifest? Any work arounds?

Issue #4 
From <https://github.com/mojaloop/interop-devops/blob/master/README_EC2.md> 
Much information here is missing in how to set up the EC2 Instance:
	1. VPC Config (does this need external access (IGW?))
	2. Subnet Config (if other than default public subnet (do we need public/private))
	3. EC2 instance sizes (can it run on anything including a t2micro?)
	4. Network Security Groups (ports if other than 80/443/22)
	5. Requirements mention nothing about needing Ansible (can ansible be run from a local machine with AWS access or needs to be run from an/the AWS ec2 instance?)

**Comment by elnyry** [comment]
We have a revamped and updated deployment guide now - http://mojaloop.io/documentation/deployment-guide/

Is this issue still applicable? @kjw000 @ladeseike

**Comment by kjw000** [comment]
we should validate with @HenkKodde  but this should be the latest.

**Comment by ManuHernz** [comment]
Hi! Everybody. Can anyone help me install Mojaloop, using AnyDesk?

**Comment by ladeseike** [comment]
Hello Kim, Sam and the rest of Mojaloop teams, thank you guys very much for the great update you have bestowed upon Mojaloop Docs since I left my comments sometimes ago.
Just to be able to test all the new updates I ordered a new laptop to use as a testing platform, still waiting for it though. I will put all these together and give Mojaloop another test very soon and believe me I will get back to you guys with feedback of how it turns out. 
From what I've seen and reviewed so far however, I am super impressed with all the efforts and very hard work all of you guys put together to answer your followers questions and tried in the process to solve major issues. Please keep up the good job. WELL DONE GUYS!!!
I promised to stay in touch and please keep me in your emailing & other contact lists...thanks....

Best Regards,
Lawrence 
still can be reached at: Ladeseike@gmail.com

**Comment by kjw000** [comment]
Thanks Lawrence.   Feel free to submit new issues to help with the documentation effort.  Also the community is meeting from Sept 10-13th in the Ivory Coast if you want the details.

**Comment by ladeseike** [comment]
Sure Kim, thank you very much for your prompt reply. You know a funny coincidence is I might be at Ivory Coast myself somewhere close to end of August at least that's the plan for now. But please send me the meeting plans and schedules and I will see if I can fit it in my schedule as well....Have a great day/week ahead....

**Comment by kjw000** [comment]
done

**Comment by ladeseike** [comment]
Thanks Kim.

**Comment by ladeseike** [comment]
Hello Kim, Sam and the Moja Team,

I sincerely hope you guys are doing well. Like I promised I have been
putting Moja back
together for few days now. Majority of what I tried so far following the
new Docs have been
fine and very easy to follow. However, like most projects of this
size/caliber it will take few
trials to arrive home. The following are few lines I will need some
help/clarifications/guidiance et al...with
and you guys answers / helps / directions will be super appreciated in
advance: Here we go...
1. Installation of Docker with Snap / Snapd (
I installed Docker with snap / snapd but trying to run it under snap is not
working for me
In the meanwhile I then removed the one with snap and installed Docker
globally on Ubuntu, working but
still not with snap commands....)
2. Installation of Mojaloop: Getting this error while trying to install
Moja/Mojaloop (
[image: image.png]
Then I tried few times to remove and re-install but still keep getting same
error message...)
3. Instructions of how to download / install / incorporate VALUES.YAML (The
old version of
Moja that I was trying to install b4 actually have a copy of Values.yaml in
a folder...that don't
really need a copy of it to be downloaded separately....But either way, I
downloaded Values
just need help with some of the values needed to be EDITED and they how to
incorporate and
use it with Moja afterwards...)
4. Installation & Integration of Postman with Mojaloop b4 getting into all
the regression testing
et al...(I also was able to install Postman but need help integrating and
using it with Moja...)

Thank you guys in advance and looking forward to hearing from you soon.

Thanks,
Lawrence Adeseike

**Comment by elnyry** [comment]
@ladeseike thanks for the feedback.

The below deployment and onboarding material has been updated last week to fix a few issues, can you please try these and out and let us know?

1. https://mojaloop.io/documentation/deployment-guide/
2. https://mojaloop.io/documentation/deployment-guide/local-setup-linux.html
3. https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md
