### ISSUE TITLE
Template User Story

### ISSUE THREAD

**Issue by kjw000** [mojaloop/mojaloop#123]
As a _customer_, I want to _solve some problem described from the customer point of view_, so that I can _accomplish some measurable outcomes_

Description as needed
- [ ] Acceptance criteria 1
- [ ] Acceptance criteria 2
- [ ] Task 1 
- [ ] Task 2 

Add to an _epic_ 
Use the _Story_ label so we can filter on stories.
Add the _estimate_, 
Add the _milestone_ due date
Put it in the Pipeline: _Backlog_ once all the above is done

**Comment by elnyry** [comment]
Added one here - https://github.com/mojaloop/docs/blob/develop/Standards/Template_Story.md
