### ISSUE TITLE
Template: Bug

### ISSUE THREAD

**Issue by kjw000** [mojaloop/mojaloop#124]
Put the bug in the appropriate repo. If the bug spans multiple repos, use the Mojaloop repo.

The title should be short, but tell what behavior is blocked or broken

Start with high level description of the bug. Include what 

Detailed steps to reproduce the bug as needed
- [ ] Repro Step 1
- [ ] Repro Step 2

These steps need only be enough information that both the developer and tester understand the steps needed.

Add environment details if relevant. 
Example:
Test Environment, using the same DFSP as the source and destination.

Use the _bug_ label so we can filter on bugs

**Comment by elnyry** [comment]
Added the template for bug here: https://github.com/mojaloop/docs/blob/develop/Standards/Template_Bug.md
