### ISSUE TITLE
Auto-populate currency table with ISO 4217 Currency codes

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#132]
**Goal**:
As a developer I would like to __Auto-populate currency table with ISO 4217 Currency codes__ so that we associate the correct currency code to participants.

**Tasks**:
- [ ] ...

**Acceptance Criteria**:
- [ ] Migration script auto populates the Currency table with ISO 4217 Currency codes
- [ ] The "currencyId" column in the Currency table must be changed to a VAR Char so that it can now store to the ISO 4217 Currency codes

**Dependencies**:
- ...

**Comment by elnyry** [comment]
Issue #208 in mojaloop/project/issues
