### ISSUE TITLE
Transfer Prepare request that exceeds the NET_DEBIT_CAP does not respond with an errorInformation message

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/mojaloop#135]
I tested a scenario where the position value exceeds net debit cap. In this scenario as per the API Spec, the payer should receive a notification at the end point - PUT /transfers/{ID}/error.

The content of the error should be in the below format.

{
  "errorInformation": {
    "errorCode": "string",
    "errorDescription": "string",
    }
  }
}

And regarding the error code and description, as per API spec, error code should be 4001.

I am finding that Payer FSP is not receiving such reject notification in this scenario.

**Comment by sri-miriyala** [comment]
Tested this feature on 08/24/208  after Development team deployed code fix. This feature is still not working according to the requirements.

**Comment by sri-miriyala** [comment]
After the code fix, payerfsp receiving error notification at the right endpoint. Can be closed after running the test scripts couple more times.

**Comment by elnyry** [comment]
Thanks Miguel and Sri
