### ISSUE TITLE
Handling of duplicate transfer in committed state

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/mojaloop#136]
When I was checking duplicate transfer handling in transfers-prepare (ML story#309), I sent a duplicate transfer with same parameters when the actual transfer is in committed state. I'm expecting a switch call back to payerfsp with a transfer success message from the actual transfer. Instead, I noticed switch is sending that transfer to payeefsp for processing and showing a committed state. Pls see below ml-adapter notification handler logs for reference.
Screen Shot 2018-08-30 at 1.38.24 AM.png

**Comment by elnyry** [comment]
Thanks Sri for creating this - https://github.com/mojaloop/project/issues/424 , lets track it there
