### ISSUE TITLE
Re-factor Central Directory micro-service for K8 Pods and Deployments utilizing K8 DNS for Service Discovery, Database, Health Probe, Configurations and Secrets

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#15]
##### Description:
Central Directory to deploy and run via a Kubernetes

##### Success Criteria:
- Define Kubernetes Deployment Templates (Pod, Services, Ingress)
- Inject Environmental Configurations via ConfigMaps into the Container Runtime
- Inject hashed sensitive information (e.g. credentials) via a Secret into the Container Runtime
- Configure Health Probe (if available)

**Comment by elnyry** [comment]
Outdated; current issues tracked here - https://github.com/mojaloop/project/issues
