### ISSUE TITLE
Create documentation to describe the automated provisioning of local development

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#17]
**Goal**:
As DevOps I want documentation on how to deploy Central components on my local development environment

**Tasks**:
- [ ] Create documentation for Central component deployment to local development environment

**Acceptance Criteria**:
- [ ] Documentation for Central component deployment to local development environment

**Dependencies**:
n/a

**Comment by mdebarros** [comment]
@NicoDuvenage I believe we should split this story into separate stories for Documentation and Automation.

Let me know what you think?

**Comment by millerabel** [comment]
Agreed

**Comment by NicoDuvenage** [comment]
Thanks guys - I will do some refinement.

**Comment by elnyry** [comment]
Onboarding documents provide instructions on how to setup the system locally or run services separately... closing this for now
