### ISSUE TITLE
Is it ready??

### ISSUE THREAD

**Issue by chegeeh** [mojaloop/mojaloop#230]
Is it ready for commercial use ??

**Comment by Eman201** [comment]
I need to apart of the mojaloop

**Comment by elnyry** [comment]
Hi, we have a press release from Mowali a Joint Venture between MTN and Orange about commercially implementing/deploying a Mojaloop based system. We also have a similar announcement from Bank of Tanzania without specifically mentioning Mojaloop.

You may have to answer this question for yourself :-), keeping in mind that we have two commercial implementations that are currently in progress which are planned to go live soon.

**Comment by elnyry** [comment]
@Eman201 how would you like to be part of Mojaloop?
