### ISSUE TITLE
Lookup parties - MSISDN not found test case giving incorrect Headers

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/mojaloop#235]
**Summary:**
When I call GET /parties /MSISDN on a MSISDN not added to the MSISDN oracle, I'm expecting a party ID not found error msg with "3200" error code with right set of Headers returned to payerfsp simulator. But payerfsp received incorrect Headers FSPIOP-Source, FSPIOP-Destination, FSPIOP-URI, FSPIOP-Method and incorrect error code and msg too.

**Expected Headers:**
1. FSPIOP-Source to be Switch since the msg is originated in Switch
2. FSPIOP-Destination to be payerfsp as payerfsp is receiving the msg
3. FSPIOP-URI to be "/parties /MSISDN /ID /error"
4. FSPIOP-Method to be "PUT"

**Actual Headers:**
1. FSPIOP-Source is payerfsp
2. FSPIOP-Destination did not return
3. FSPIOP-URI did not return
4. FSPIOP-Method did not return

Error code returned should be 3200 with msg Generic ID error provided by the client which is generic ID not found but received 3204 with msg Party with the provided identifier, identifier type, and optional sub id or type was not found.

**Logs from ALS:**
[d1648-account-lookup-service-6875d999b8-65pbj account-lookup-service] 2019-07-28T03:01:28.209Z - debug: participant endpoint url: http://dev1-simulator.mojaloop.live/payerfsp/parties/MSISDN/10000000/error for endpoint type FSPIOP_CALLBACK_URL_PARTIES_PUT_ERROR
[d1648-account-lookup-service-6875d999b8-65pbj account-lookup-service] 2019-07-28T03:01:28.209Z - debug: sendRequest::request {"url":"http://dev1-simulator.mojaloop.live/payerfsp/parties/MSISDN/10000000/error","method":"PUT","headers":{"connection":"close","x-request-id":"4835f952cd7f5aede1591be8e363e1c3","x-real-ip":"10.1.2.119","x-forwarded-for":"10.1.2.119","x-forwarded-host":"dev1-account-lookup.mojaloop.live","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/parties/MSISDN/10000000","x-scheme":"http","date":"Sun, 28 Jul 2019 03:01:28 GMT","fspiop-source":"payerfsp","content-type":"application/vnd.interoperability.parties+json;version=1.0","user-agent":"PostmanRuntime/7.15.2","accept-encoding":"gzip, deflate"},"data":{"errorInformation":{"errorCode":"3204","errorDescription":"Party with the provided identifier, identifier type, and optional sub id or type was not found.","extensionList":[{"key":"MSISDN","value":"10000000"}]}},"responseType":"json"}

**Comment by elnyry** [comment]
@sri-miriyala I agree the issue about the headers but the error code looks good to me.. I do not see it as a bug. If a scheme needs to abstract information, 3200 may be used, but I do not see it in ALS why it would be a concern (security or otherwise) .. In fact 3200 doesn't talk about what kind of ID it is (transfer ID ? quote ID? etc)

@rmothilal FYI

**Comment by sri-miriyala** [comment]
Issue moved to [mojaloop/project #883](https://github.com/mojaloop/project/issues/883) via [**ZenHub**](https://www.zenhub.com/)
