### ISSUE TITLE
ALS PUT /parties/MSISDN/{ID}/error gives a 400 Bad request for a valid request

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/mojaloop#236]
Expected Behavior:
    Submitting a valid PUT request to /parties/MSISDN/{ID}/error endpoint on ALS service, should result in a 200.

Actual Behavior:
    Above request is resulting in a 400 Bad Request response.

Steps to reproduce:
    1. submit the below curl request
       curl -X PUT \
  http://dev1-account-lookup.mojaloop.live/parties/MSISDN/17855501914/error \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 280' \
  -H 'Content-Type: application/vnd.interoperability.parties+json;version=1.0' \
  -H 'Date: Sun, 28 Jul 2019 15:05:38 GMT' \
  -H 'FSPIOP-Destination: payerfsp' \
  -H 'FSPIOP-Source: payeefsp' \
  -H 'Host: dev1-account-lookup.mojaloop.live' \
  -H 'User-Agent: PostmanRuntime/7.15.2' \
  -d '{
  "errorInformation": {
    "errorCode": "3204",
    "errorDescription": "Party with the provided identifier, identifier type, and optional sub id or type was not found.",
    "extensionList": [
      {
        "key": "MSISDN",
        "value": "17855501914"
      }
    ]
  }
}'
   2. You will notice that the response is a 400 Bad Request instead of a 200.
        Response I received during my testing
        {
    "statusCode": 400,
    "error": "Bad Request",
    "message": {
        "errorInformation": {
            "errorDescription": "Invalid request payload input",
            "extensionList": [
                {
                    "key": "",
                    "value": ""
                }
            ]
        }
    }
}

**Comment by elnyry** [comment]
maybe a feature request if /error on /parties wasn't implemented.. would be a bug if thats implemented... @rmothilal

**Comment by sri-miriyala** [comment]
Issue moved to [mojaloop/project #884](https://github.com/mojaloop/project/issues/884) via [**ZenHub**](https://www.zenhub.com/)
