### ISSUE TITLE
Enable Participant Roles

### ISSUE THREAD

**Issue by JoSowden** [mojaloop/mojaloop#259]
This epic will allow participant to have role types. The role type will determine what data needs to be stored about it and what functions it has access to.

Define Role Types
There should be the ability to give a DFSP a role.
This role will then determine which functions it can perform
This role will then determine what data needs to be stored about the participant
 Possibly use OAuth  and limiting the endpoints access 
 NB :Security Input is required

**Comment by lewisdaly** [comment]
This will be covered outside of PISP work. So happy to close this for MVP.
