### ISSUE TITLE
Update PISP local docker setup with on-boarding instructions

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#295]
As a developer I want to gain a quick understanding of the mojaloop services and setup of docker compose.

Tasks:

- [ ] List any dependencies to run the setup.
- [ ] Add a diagram depicting services, dfsps, etc and their ports.

**Comment by lewisdaly** [comment]
@kleyow to update this tickets to conform to the template.

**Comment by eoln** [comment]
@kleyow diagram updated: https://github.com/eoln/pisp/tree/docs/295_docker-local_onboarding/docker-local
