### ISSUE TITLE
Slack is a closed discussion group

### ISSUE THREAD

**Issue by kevin-biot** [mojaloop/mojaloop#3]
https://leveloneproject.slack.com is only open to certain companies, therefore impossible for others to join or contribute to for example architectural discussions and roadmaps.

**Comment by kjw000** [comment]
@kevin-biot.  we discussed the issues with Slack and we are looking at other communication tools that can be leveraged by everyone.  LMK if you have any suggestions.  We are looking at a few and for now have invited you to the leveloneproject via email.

**Comment by kevin-biot** [comment]
if the discussion is triggered, I'll close this, as that was the intention ......
