### ISSUE TITLE
Account lookup service needs to be run twice to setup properly in docker local setup.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#300]
**Summary**:
Account lookup service needs to be setup with an initial `docker-compose up account-lookup-service`. 

The issue looks like the MySQL Database config for the ALS when running the first time. 

**Severity**:
Low

**Priority**:
Meduim

**Expected Behavior**
Account lookup service's endpoint `/health` should be healthy after its first run.

**Steps to Reproduce**
  1. `docker-compose down`
  2. `docker-compose up account-lookup-service` on a clean docker run
  3. curl -L -X GET 'http://172.17.0.1:4001/health' will say that the service is "DOWN"

**Specifications**
  - Component (if known): Account lookup service
  - Version:
  - Platform: 
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: Kevin Leyow

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by kleyow** [comment]
@lewisdaly I'm having no issues on Linux with this so I believe this is done.

**Comment by lewisdaly** [comment]
There are a couple things here:

1. The ALS Health checks themselves seem to fail on the first run. This is something to be fixed in the ALS service
2. The wait4 script is depending on `central-ledger`, which is probably what we want, but the health checks in ALS don't have this dependency, which I find is a little confusing.

**Comment by lewisdaly** [comment]
It appears the migrations for ALS are run on the first start, but knex doesn't re-connect, or register that the migrations have been run. 

This causes the health check (which looks at the `migration_lock` table) to fail, since it thinks there are no tables at all in the db.

**Comment by lewisdaly** [comment]
This PR will hopefully fix it: 

https://github.com/mojaloop/pisp/pull/22

I'm testing on ci/cd now
