### ISSUE TITLE
Create a singular command to run the local docker setup, rest call setup and tests.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#301]
## **Goal**:
As a developer I would like singular command to run the local docker setup, rest call setup and tests.

**Tasks**:
- [ ] Create a singular command to setup local docker and run tests.

**Acceptance Criteria**:
- [ ] Singular command made that runs local docker, local setup and runs tests.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Will be covered in #279
