### ISSUE TITLE
Update services to use OpenApi Snippets library.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#353]
## **Goal**:
As a **Developer**  **I want to** update services to use the api snippets library  **so that I can** leverage it's maintainability for swagger definitions.

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Change to common elements is reflected in dependent APIs

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Which services? Perhaps this ticket could just be for 1 service.

**Comment by kleyow** [comment]
For the three services we are mostly touching. sdk-scheme-adapter, auth-service and thirdparty-api-adapter. I'll separate this into 3 tickets.
