### ISSUE TITLE
Determine where to do CVS, Documentation and Agile Project Management

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#37]
Determine if we need to use Mojaloop, L1P, ModusBox's Bitbucket or a private Bitbucket account for version control of Source.

Also, determine where to store project documentation.

Determine what to use as an Agile Project Management system.

Determine if we want to invite public participation and contribution on the project.

After facts for all of the above have been gathered and verified, execute it on the chosen platforms.

**Comment by elnyry** [comment]
Outdated; current issues tracked here - https://github.com/mojaloop/project/issues
