### ISSUE TITLE
Update mojaloop/thirdparty-api-adapter to use mojaloop/api-snippets.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#389]
## **Goal**:
As a developer I want to use api-snippets for open api schemas so that leverage it's maintainability and one source of truth-ness.

**Tasks**:
- [ ] Update any interfaces in service to use api-snippets.

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This is done already, thanks @sridharvoruganti
