### ISSUE TITLE
hapi-openapi is can't find handlers with path components that end with `ts`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#392]
**Summary**:
In noticed while implementing #363 that when I named the handler for `POST thirdpartyRequests/transactions/{ID}/authorizations`, the `thirdpartyRequests` root was not being found by hapi-openapi.

Following the normal hapi-openapi conventions, we have files and directories arranged to follow the resource path. So for the above request, we have the following directory structure:
```
server/handlers/thirdpartyRequests/transactions/{ID}/authorizations.ts #<--- this is where we implement our handler
```
It looks like internally, when we specify the `ts` extension, the `merge-object-files` that `hapi-openapi` uses removes the the `ts` from the end of the directory named `thirdpartyRequests`, which makes `hapi-openapi` unable to resolve the authorizations handlers.

When I added some basic logging to the `hapi-openapi` library, I could see the following handlers resolved like so:
```js
{
  health: { get: [AsyncFunction] },
  hello: { get: [AsyncFunction: get] },
  metrics: { get: [Function: get] },
  onPreHandler: { default: [AsyncFunction: onPreHandler] },
  onValidateFail: { default: [Function: onValidateFail] },
  thirdpartyReque: { transactions: { '{ID}': [Object] } }
}
```

Any other name works,  eg:
```
tpr
thirdpartyRequest
thirdpartyrequestS
```

For now, I'm going to leave the handler as `/tpr/...` until we can find a fix. That way the fact that the path is incorrect is very obvious, and hopefully won't lead to subtle capitalization errors.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
The handlers should resolve correctly for resources containing the substring`ts`

**Steps to Reproduce**
  1. Add any handler to a swagger file with a path ending in `ts`, eg. `thirdpartyRequests/transactions/{ID}/authorizations`
  2. Observe that `hapi-openapi` doesn't find the handler

**Specifications**
  - Component (if known): thirdparty-api-adapter
  - Version: "hapi-openapi": "^2.0.2",
  - Platform: MacOS
  - Type of testing: unit
  - Bug found/raised by: @lewisdaly 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by lewisdaly** [comment]
@eoln @sridharvoruganti is this now out of scope since we have moved away from `hapi-openapi`?

**Comment by eoln** [comment]
yes, @sridharvoruganti work is using openapi-backend and no more facing TS issue
