### ISSUE TITLE
Date header missing from the Switch signature in timeout scenario

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/mojaloop#429]
**Summary**:
When we validated the timeout scenario after the JWS signature generation capability in switch, found that the Date header is missing from the protected headers.
**Severity**:
High
**Priority**:
Critical
**Expected Behavior**
The JWS signature should contain the Date header in protected headers. 

**Steps to Reproduce**
  1. Send POST /quotes request from happy path
  2. Send POST /transfers request from happy path by modifying the transferExpiration from the pre-request script. Change that to 1.2 sec instead of 60 sec like below.
pm.environment.set("transferExpiration",new Date(new Date().getTime() + 1200))

  3. Check the logs at payerfsp, payeefsp

Response:
{
    "headers": {
        "host": "dev1-sim-payerfsp.mojaloop.live",
        "connection": "close",
        "x-request-id": "a96198f184a6bebc442796f1c7b94afa",
        "x-real-ip": "10.1.2.224",
        "x-forwarded-for": "10.1.2.224",
        "x-forwarded-host": "dev1-sim-payerfsp.mojaloop.live",
        "x-forwarded-port": "80",
        "x-forwarded-proto": "http",
        "x-original-uri": "/sim/payerfsp/inbound/transfers/4f1c5723-c62b-4204-b4b4-93fc06916af7/error",
        "x-scheme": "http",
        "content-length": 84,
        "content-type": "application/vnd.interoperability.transfers+json;version=1.0",
        "accept": "application/vnd.interoperability.transfers+json;version=1.0",
        "fspiop-destination": "payerfsp",
        "date": "Tue, 15 Sep 2020 18:08:30 GMT",
        "fspiop-source": "switch",
        "fspiop-http-method": "PUT",
        "fspiop-uri": "/transfers/4f1c5723-c62b-4204-b4b4-93fc06916af7/error",
        "fspiop-signature": "{\"signature\":\"LO4WH3XpelRSM5uE18PLW8tqMDKbzv4WqznTWsxNfMdmmDjWwhPGVdoLuvrhXBA1z34LK3b3N2McOm9tAUL9wFz-Y3qHOo1dBztFqJDqqc1wRAoJ-FQOHiQu2HiUeBEaH3i9tEZWANf_UUJl9PRM-8LU8sH6qjW5nbxEaXwGLsa_-AwNr0KO_OEQRkqyRhFAK1wCmlBST3f_0bey6JOAV1XE9vdI1Ej4NvZ8vfhMGxN4SJhGp-UB3MK7IuK90zXJcZPeHME2OUcle-wr2adcnGxX_1yVz1IneE_ltitcIGAnS648kIB9DTV_AqRBqqx-b_CEFh0VIZwSAapVOuVddA\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzLzRmMWM1NzIzLWM2MmItNDIwNC1iNGI0LTkzZmMwNjkxNmFmNy9lcnJvciIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCJ9\"}",
        "traceparent": "00-de64620a0f4d8bd80ed262e2b78d739a-1db745b8b7007ca0-00",
        "tracestate": "mojaloop=eyJzcGFuSWQiOiIxZGI3NDViOGI3MDA3Y2EwIn0=",
        "user-agent": "axios/0.19.2"
    },
    "data": {
        "errorInformation": {
            "errorCode": "3300",
            "errorDescription": "Generic expired error"
        }
    }
}

Screenshot:
![image (2)](https://user-images.githubusercontent.com/38143240/93473759-65000500-f8c4-11ea-9925-169b381bfe0f.png)

**Specifications**
  - Component (if known): ml-api-adapter, CL
  - Version: latest
  - Platform: Mac
  - Subsystem:
  - Type of testing: Feature
  - Bug found/raised by: Sri & Egor

**Notes**:
The scripts will be pushed to OSS-Features-tests folder and can be found if search by TC10.

- Severity when opened:
- Priority when opened:

**Comment by sri-miriyala** [comment]
Created here: https://github.com/mojaloop/project/issues/1709
hence closing

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1823](https://github.com/mojaloop/project/issues/1823) via [**ZenHub**](https://www.zenhub.com/)
