### ISSUE TITLE
Write event-based operation to email settlement detail via csv to each DFSP

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#47]
##### Description:
Write event-based operation to email settlement detail via csv to each DFSP
##### Success Criteria:
- During the settlement process, the underlying transfer detail making up the settlement batch is split into csv files for each DFSP.
- Each of the csv files are emailed to the relevant DFSP.

**Comment by NicoDuvenage** [comment]
Part of this story would be to extend the table (Accounts) to cater for an email address. This is done by adding it directly to the table but another user-story on the backlog will take care of the refactoring of the database where proper database principles will be followed where there will be a separate table with the contact details, a table with Communication Types and then an associative table linking an account to a specific contact detail record.

**Comment by elnyry** [comment]
Use mojaloop/project/issues to track issues now
