### ISSUE TITLE
Enhance Central Ledger Functionality

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#53]
Business Functionality - Add more capabilities like:
-Dynamic rule based settlement
-Changing DFSP working capital

Technical Functionality - Add more capabilities like:
-Load Balancing and scalability
-Refactor for possible microservices implementation

**Comment by millerabel** [comment]
This feels like an epic, but ought to be more specific. It may need to be factored into several stories. How would we size this and how would we know when we’re done?

**Comment by NicoDuvenage** [comment]
Miller,

That is an epic. If you open it you'll see the user stories making it
possible. In total there are 11 epics and just over 70 user stories.

The next step is to refine the issue names as the initial pass was just to
get placeholders there. Next would be to define success criteria and
definition of done, then prioritise and lastly to fill in the estimates.

Thanks,
Nico Duvenage

**Comment by millerabel** [comment]
Thanks Nico.

**Comment by elnyry** [comment]
Use mojaloop/project/issues to track issues now
