### ISSUE TITLE
Consider breaking up Ledger to fine-grained micro-services

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#58]
Consider breaking up Ledger to fine-grained micro-services if scalability is not adequate. This will allow for higher level of parallel processing.ß this will require an API gateway to consolidate the service offerings.

**Comment by kevin-biot** [comment]
Which ledger? Focus should be on the central ledger as you will do many unknown integrations to MFS platforms. They in a sense behind their own API are the ledger. So any calls to a local sending ledger will in fact be a call to a MFS platform. No MFS platform will in fact implement a ledger in front of their platform. Internally they will lock a balance on their platform, and then interact with external elements via the API's available.

**Comment by elnyry** [comment]
Use mojaloop/project/issues to track issues now
