### ISSUE TITLE
Dockerize Micro-Services - KMS

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#6]
##### Description:
Central-KMS API to run via Docker

##### Success Criteria:
- Dockerfile recipe for KMS which executes the SBT/Scala Code under Java 8.
- Docker image successfully created for KMS API
- Docker image can be executed to run the KMS API
- Publish Docker Image to https://hub.docker.com/r/mojaloop

**Comment by mdebarros** [comment]
Success Criteria:
1. Docker image for KMS which executes the SBT/Scala Code under Java 8.
