### ISSUE TITLE
Consider alternative Databases such as NoSQL (Distributed) solutions if scalability, DR, performance durability and transactionality requirements are not met with PostgreSQL

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#64]
Consider alternative Databases such as NoSQL (Distributed) solutions if scalability, DR, performance durability and transactionality requirements are not met with PostgreSQL

**Comment by kevin-biot** [comment]
currently in Kenya MPESA platform on existing hardware and Oracle can scale to 900 TPS. In Tanzania about 8% of transactions are interop. So for the near term in markets that are Kenya size 2000 TPS is probably OK. Tanzania might be hitting 1000 TPS peak across all MFS products.....

The key need is replication as in Dataguard in sync mode, so zero data loss in hardware losses or datacenter loss. With MPESA, all transactions enter a front end queue, and queues can be configured for each service or transaction type, or partner connection. SO not sure you need to go to the level of NoSQL today.

**Comment by kevin-biot** [comment]
Just did some GSMA calculations, they estimate the average global MM transaction rate is 500 TPS. So we can assume for quite some time, interop transaction rates will be low. No need to drastically over engineer?

**Comment by millerabel** [comment]
@kevin-biot, yes the 500tps is annualized global average mobile money transaction rate, by my calculation as well. The peaks will be much higher. And we must hold to human sense of real-time experience (< 5 seconds response time to confirm a released payment), even under load.

At present, Mojaloop performs ~150-200tps steady-state at the central ledger, on small hardware and without optimizations. Much less at the edges, and we're working to improve the on-ramps. But the goal is to setup the architecture for scale potential. And there are other projects under evaluation that will be take us beyond the Tanzania scale.

**Comment by elnyry** [comment]
Use mojaloop/project/issues to track issues now
