### ISSUE TITLE
Integrate Error Handling with Logging/Auditing event handlers

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#70]
Integrate Error Handling with Logging/Auditing event handlers

**Comment by kevin-biot** [comment]
It is preferable for operations to have a central logging facility. trying to grep various module log files is a nightmare. Operations staff need to be able to respond to transaction queries or failure rapidly ....

**Comment by ksatya77** [comment]
Yes, we do have it. We use ELK stack for central logging. It supports a nice query language to filter the information. Will incorporate it in mojaloop.

**Comment by elnyry** [comment]
Outdated; current issues tracked here - https://github.com/mojaloop/project/issues (Yes we do have stories for ELK, Logging, which hopefully will be prioritized in Phase3
