### ISSUE TITLE
Transaction Processing to identify, detect and review high-risk transactions based on unique risk profiles 

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#83]

**Comment by kevin-biot** [comment]
pragmatically in poor countries, most if not all MFS platforms do not do real time AML. So should risk and AML etc be done in batch offline? Each end of a transaction will have its own AML function. 

Need better use case definitions to define high risk scenarios ..... 

An easier way is to use a replicated reporting database, plug in AML etc to that and over a schedule you can generate a transaction/user black list. 

At the input end, the connections payment system should have contract obligations to verify higher value transactions for proper AML conformance. So is this a business process or a technical solution   trying to mitigate business processes that should exist?

**Comment by NicoDuvenage** [comment]
Kevin,

Thank you very much for your comments and observations. It is appreciated.

Nico Duvenage

**Comment by elnyry** [comment]
Use mojaloop/project/issues to track issues now
