### ISSUE TITLE
 Moving Central components from docker links which is to be deprecated soon

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#94]
##### Description:
 Moving Central components from docker links which is to be deprecated soon
##### Success Criteria:
- IST components communicate with the DB and function as expected with links replaced by docker_network

**Comment by jeffplesko** [comment]
Completed, tested and checked in

**Comment by mdebarros** [comment]
@jeffplesko do you need a review for this so we can move it to "done"?

**Comment by jeffplesko** [comment]
This needs to be closed out, so if a review is required, lets do it.
