### ISSUE TITLE
Refactoring Vagrant and Ansible to reflect the renaming of CST to IST

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#95]
##### Description:
Refactoring Vagrant and Ansible to reflect the renaming of CST to IST
##### Success Criteria:
- Mojaloop functions (dfsp transfers, invoicing, bulk transfers) still work after renaming host and internal naming.  Will be tested by a clean install, the above 3 tests, and uninstall to prove all aspects still work

**Comment by jeffplesko** [comment]
Completed, tested and checked in

**Comment by mdebarros** [comment]
@jeffplesko do you need a review for this so we can move it to "done"?

**Comment by jeffplesko** [comment]
This needs to be closed out, so if a review is required, lets do it.

**Comment by elnyry** [comment]
Outdated; current issues are tracked here - https://github.com/mojaloop/project/issues
